import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


import { Toaster } from "react-hot-toast";


import { VisualEditing } from "next-sanity";


import { draftMode } from "next/headers";
import DisableDraftMode from "@/components/DisableDraftMode";
import ChatIcon from "@/components/new/ChatIcon";
import SmartAssistantBubble from "@/components/SmartAssistantBubble";

export const metadata: Metadata = {
  title: "Ecommerce App for Shoppers",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {(await draftMode()).isEnabled && (
        <>
          <DisableDraftMode />
          <VisualEditing />
        </>
      )}
      <Header />
      {children}
      <SmartAssistantBubble/>
      <Footer />
      <Toaster
        position="bottom-right"
        toastOptions={{
          style: {
            background: "#000000",
            color: "#fff",
          },
        }}
      />
      <ChatIcon />
    </div>
  );
}